### ISSUE TITLE
Unexpected "Relationship has been deleted in this transaction"

### ISSUE THREAD

**Issue by cmorgner** [neo4j/neo4j-java-driver#212]
When I create two nodes and a relationship (each one with a separate statement) in an empty database, and delete the relationship in the same transaction, I get an unexpected "Relationship with id 0 has been deleted in this transaction" exception when commiting the transaction.

~~I was not able to reproduce the error using only the neo4j-java-driver, so the problem seems to exist somewhere in the way our wrapping code executes the individual statements.~~

I was hoping that you can shed some light on what happens in the database if I provide the unencrypted tcpdump of the transaction:

[bolt-transaction.txt](https://github.com/neo4j/neo4j-java-driver/files/411517/bolt-transaction.txt)

Please feel free to close the issue if this is the wrong place for this kind of question!

Thanks and best regards,
Christian

**Comment by cmorgner** [comment]
**Update**
I was able to reproduce the issue with a clean database and the neo4j-java-driver. The following class can be used to provoke the unexpected exception:

``` java
public class Delete {

    public static void main(final String[] args) {

        try (final Driver driver = GraphDatabase.driver("bolt://localhost:7687",
                        AuthTokens.basic("neo4j", "test"),
                        Config.build().withEncryptionLevel(Config.EncryptionLevel.NONE).toConfig()
            )) {

            try (final Session session = driver.session()) {

                try (final Transaction tx = session.beginTransaction()) {

                    final Node startNode          = getNodeFromStatement(tx, "CREATE (n) RETURN n", Collections.EMPTY_MAP);
                    final Node endNode            = getNodeFromStatement(tx, "CREATE (n) RETURN n", Collections.EMPTY_MAP);
                    final Map<String, Object> map = new HashMap<>();

                    map.put("id1", startNode.id());
                    map.put("id2", endNode.id());

                    final Relationship relationship = getRelationshipFromStatement(tx, "MATCH (n), (m) WHERE ID(n) = {id1} AND ID(m) = {id2} CREATE (n)-[r:TEST]->(m) RETURN r", map);

                    System.out.println("ID1: " + startNode.id());
                    System.out.println("ID2: " + endNode.id());
                    System.out.println("ID3: " + relationship.id());

                    map.clear();
                    map.put("id", relationship.id());

                    tx.run("MATCH ()-[r:TEST]-() WHERE ID(r) = {id} DELETE r", map);

                    tx.success();
                }
            }
        }
    }

    private static Node getNodeFromStatement(final Transaction tx, final String statement, final Map<String, Object> map) {
        return tx.run(statement, map).single().get(0).asNode();
    }

    private static Relationship getRelationshipFromStatement(final Transaction tx, final String statement, final Map<String, Object> map) {
        return tx.run(statement, map).single().get(0).asRelationship();
    }
}
```

The above code yields the following result:

```
--- exec-maven-plugin:1.2.1:exec (default-cli) @ neo4j-freeze-test ---
ID1: 0
ID2: 1
ID3: 0
Exception in thread "main" org.neo4j.driver.v1.exceptions.ClientException: Relationship with id 0 has been deleted in this transaction
    at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:456)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:417)
    at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
    at org.neo4j.driver.internal.connector.socket.SocketClient.receiveAll(SocketClient.java:124)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveAll(SocketConnection.java:121)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:100)
    at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:122)
    at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:144)
    at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:110)
    at org.structr.test.Delete.main(Delete.java:57)
```

The following change in the DELETE Cypher statement causes the error:

**Works**
`MATCH ()-[r]-() WHERE ID(r) = {id} DELETE r`

**Fails**
`MATCH ()-[r:TEST]-() WHERE ID(r) = {id} DELETE r`

**Comment by technige** [comment]
Thanks for raising this. We've added it to our list to investigate.

**Comment by pontusmelke** [comment]
It turns out that this is not an issue with the driver but an issue with neo4j server. I have opened a PR to have it fixed, https://github.com/neo4j/neo4j/pull/7796. As a workaround you can use a directed `MATCH`, e.g.

```
MATCH ()-[r:TEST]->() WHERE ID(r) = {id} DELETE r
```

The problem you are hitting is that the undirected match will match and try to delete the relationship twice, and on the second attempt it throws an exception since the relationship has already been deleted. 

Thanks for raising this issue!

**Comment by pontusmelke** [comment]
A fix has been merged and will go out with the next patch release of neo4j server, I'll close this issue but please feel free to reopen or open a new issue if you have more issues.
