### ISSUE TITLE
Exception when using neo4j-java-driver as part of hibernate-ogm

### ISSUE THREAD

**Issue by Restage** [neo4j/neo4j-java-driver#261]
Some weeks ago hibernate-ogm has been released in version 5.1.0.Alpha1. The release added support for connecting to neo4j servers via bolt by making use of neo4j-java-driver.

I tried to use this new feature but ran into a problem which seems to be caused by the driver (but I'm not 100% sure about this).

Starting my glassfish I get the following exception:

``` java
java.util.ServiceConfigurationError: org.neo4j.driver.internal.spi.Connector: Provider org.neo4j.driver.internal.connector.socket.SocketConnector not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.neo4j.driver.internal.pool.InternalConnectionPool.loadConnectors(InternalConnectionPool.java:145)
    at org.neo4j.driver.internal.pool.InternalConnectionPool.<init>(InternalConnectionPool.java:77)
    at org.neo4j.driver.internal.InternalDriver.<init>(InternalDriver.java:41)
    at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:128)
    at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:112)
    at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:87)
    at org.hibernate.ogm.datastore.neo4j.remote.bolt.impl.BoltNeo4jClient.createNeo4jDriver(BoltNeo4jClient.java:39)
    at org.hibernate.ogm.datastore.neo4j.remote.bolt.impl.BoltNeo4jClient.<init>(BoltNeo4jClient.java:32)
    at org.hibernate.ogm.datastore.neo4j.remote.bolt.impl.BoltNeo4jDatastoreProvider.start(BoltNeo4jDatastoreProvider.java:57)
```

I am suprised about this message since `SocketConnector` is a subtype of `Connector` and the service seems to be correctly configured under **META-INF.services**.

The code which causes the failure is located in the `java.util.ServiceLoader:375`:

``` java
if (!service.isAssignableFrom(c)) {
    fail(service, "Provider " + cn  + " not a subtype");
}
```

Is this a bug in the driver, might it be a configuration error in my project or is it likely a problem in hibernate-ogm? The framework uses version 1.0.4. of neo4j-java-driver.

**Update:** I have seen that the service definition has been refactored with release 1.1.0-M6. Using this version the exception no longer appears. Nevertheless I am interessed what's the problem with version 1.1.0-M5 and beyond.

**Update 2:** An example to reproduce this issue can be found in my repository: https://github.com/Restage/HibernateOgmExample
Just run a Neo4j instance with the parameters given in the persistence.xml. If you than start the ear on a glassfish4 the exception should be shown.

**Comment by zhenlineo** [comment]
Hi, would you mind raising this issue to hibernate-ogm project instead? I not really understand the framework so it is really hard for me to look what could be the problem. I think it would be better to ask the hibernate-ogm? If they provide the support to use neo4j-java-driver, then they might know more how to help you?

It might be related to META-INF.services as you pointed out. But as for the users who depends on this driver with a simple mvn dependency, they do not have this problem, maybe some config is wrong either in hibernate or your project?

Cheers,
Zhen

**Comment by technige** [comment]
Closing as fixed in M06.
