### ISSUE TITLE
maven dependency failure

### ISSUE THREAD

**Issue by Hassanbenlebsir** [neo4j/neo4j-java-driver#274]
I want to make a simple connection to neo4j using the neo4j-java-driver.
i created a maven folder and added the dependency in the pom.xml:

**This is my pom.xml file:**
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-app</name>
  <url>http://maven.apache.org</url>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.2</version>
        </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>org.neo4j.driver</groupId>
      <artifactId>neo4j-java-driver</artifactId>
      <version>1.0.6</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>

```
**and this is my java code:**

```
package com.mycompany.app;
import org.neo4j.driver.v1.*;
class App 
{
    public static void main( String[] args )
    {
    	Driver driver = GraphDatabase.driver( "bolt://localhost:7687", AuthTokens.basic( "neo4j", "admin1234" ) );
		Session session = driver.session();

		session.run( "CREATE (a:Person {name:'Arthur', title:'King'})" );

		StatementResult result = session.run( "MATCH (a:Person) WHERE a.name = 'Arthur' RETURN a.name AS name, a.title AS title" );
        System.out.println( "Hello World hassan again!" );
    }
}
```

**and this is the error after running it:** 
Exception in thread "main" java.lang.NoClassDefFoundError: org/neo4j/driver/v1/AuthTokens
	at com.mycompany.app.App.main(App.java:13)
Caused by: java.lang.ClassNotFoundException: org.neo4j.driver.v1.AuthTokens
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**and this is the poutput for mvn depedency:tree**

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.2:tree (default-cli) @ my-app ---
[INFO] com.mycompany.app:my-app:jar:1.0-SNAPSHOT
[INFO] +- org.neo4j.driver:neo4j-java-driver:jar:1.0.6:compile
[INFO] \- junit:junit:jar:3.8.1:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.257s
[INFO] Finished at: Fri Nov 18 04:26:24 EST 2016
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------

**Comment by zhenlineo** [comment]
I did not get any problem with your pom and example main class :<

```
mvn clean install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ my-app ---
[INFO] Deleting /Users/xx/git/my-app/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-app ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ my-app ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /Users/XX/git/my-app/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ my-app ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/XX/git/my-app/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ my-app ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ my-app ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ my-app ---
[INFO] Building jar: /Users/XX/git/my-app/target/my-app-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ my-app ---
[INFO] Installing /Users/XX/git/my-app/target/my-app-1.0-SNAPSHOT.jar to /Users/XX/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar
[INFO] Installing /Users/XX/git/my-app/pom.xml to /Users/XX/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.433 s
[INFO] Finished at: 2016-11-18T10:45:52+01:00
[INFO] Final Memory: 14M/210M
[INFO] ------------------------------------------------------------------------
```

Maybe try to update mvn?

**Comment by Hassanbenlebsir** [comment]
i'm on centos i'm trying yum update mvn but it didn't work

```
 yum update maven
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Setting up Update Process
Loading mirror speeds from cached hostfile
 * base: mirrors.coreix.net
 * centosplus: mirrors.clouvider.net
 * epel: mirrors.coreix.net
 * extras: mirror.vorboss.net
 * updates: mirrors.coreix.net
No Match for argument: maven
No package maven available.
No Packages marked for Update
```

**this is my maven version**

```
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 08:51:28-0500)
Maven home: /usr/local/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_102/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "2.6.32-642.6.2.el6.centos.plus.x86_64", arch: "amd64", family: "unix"
```

**Comment by Hassanbenlebsir** [comment]
I updated my maven still same error:

```
[root@localhost my-app]# mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /opt/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_102/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "2.6.32-642.6.2.el6.centos.plus.x86_64", arch: "amd64", family: "unix"
```

**Comment by jexp** [comment]
Are you running the app via Maven? or how do you start it?

`mvn exec:java -Dexec.mainClass="com.mycompany.app.App"`

if you don't run it via maven you have to provide all the library / classpath dependencies to your runner.

**Comment by Hassanbenlebsir** [comment]
Thank you that's what i was doing wrong.
`mvn exec:java -Dexec.mainClass="com.mycompany.app.App`
worked like a charm
