### ISSUE TITLE
PackStream$Unexpected exception when trying to do performance benchmark

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j-java-driver#29]
Hi,

I integrated NDP as transport layer in our Neo4j access layer. Also I created performance tests.
JMH is used as performance test runner.

Performance test explanation - before test execution we create `X` nodes. Inside test method we query all `X` nodes.

Code example:
```java
// Driver is wrapped into our code
@Benchmark
public void getNodesNdp(World world, Blackhole bh) {
    try (Transaction tx = world.serverNdpDb().beginTx()) {
        Result nodes = world.serverNdpDb().execute(GET_NODES_QUERY);
        while (nodes.hasNext()) {
            Map<String, Object> next = nodes.next();
            bh.consume(next);
        }
        tx.success();
    }
}
```

### `X` = 1
```
# JMH 1.9.3 (released 35 days ago)
# VM invoker: /usr/lib/jvm/java-7-oracle/jre/bin/java
# VM options: -Xmx1024m -Xms1024m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -XX:hashCode=5 -DprepareNodeCount=1
# Warmup: 2 iterations, 30 s each
# Measurement: 3 iterations, 30 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: GetNodesBenchmark.getNodesNdp

# Run progress: 0.00% complete, ETA 00:02:30
# Fork: 1 of 1
# Warmup Iteration   1: 0.849 ms/op
# Warmup Iteration   2: 0.450 ms/op
Iteration   1: 0.475 ms/op
Iteration   2: 0.469 ms/op
Iteration   3: 0.536 ms/op


Result "getNodesNdp":
  0.493 ±(99.9%) 0.673 ms/op [Average]
  (min, avg, max) = (0.469, 0.493, 0.536), stdev = 0.037
  CI (99.9%): [≈ 0, 1.166] (assumes normal distribution)


# Run complete. Total time: 00:02:41

Benchmark                      Mode  Cnt  Score   Error  Units
GetNodesBenchmark.getNodesNdp  avgt    3  0.493 ± 0.673  ms/op
```

### `X` = 100
```
# JMH 1.9.3 (released 35 days ago)
# VM invoker: /usr/lib/jvm/java-7-oracle/jre/bin/java
# VM options: -Xmx1024m -Xms1024m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -XX:hashCode=5 -DprepareNodeCount=100
# Warmup: 2 iterations, 30 s each
# Measurement: 3 iterations, 30 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: GetNodesBenchmark.getNodesNdp

# Run progress: 0.00% complete, ETA 00:02:30
# Fork: 1 of 1
# Warmup Iteration   1: 4.197 ms/op
# Warmup Iteration   2: 2.193 ms/op
Iteration   1: 2.024 ms/op
Iteration   2: 1.778 ms/op
Iteration   3: 1.830 ms/op


Result "getNodesNdp":
  1.877 ±(99.9%) 2.367 ms/op [Average]
  (min, avg, max) = (1.778, 1.877, 2.024), stdev = 0.130
  CI (99.9%): [≈ 0, 4.244] (assumes normal distribution)


# Run complete. Total time: 00:02:47

Benchmark                      Mode  Cnt  Score   Error  Units
GetNodesBenchmark.getNodesNdp  avgt    3  1.877 ± 2.367  ms/op
```

### `X` = 500
And here we got an **exception**.
Note: the only one thing that we changed is how many nodes we have in our database.

```
# JMH 1.9.3 (released 35 days ago)
# VM invoker: /usr/lib/jvm/java-7-oracle/jre/bin/java
# VM options: -Xmx1024m -Xms1024m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -XX:hashCode=5 -DprepareNodeCount=500
# Warmup: 2 iterations, 30 s each
# Measurement: 3 iterations, 30 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: GetNodesBenchmark.getNodesNdp

# Run progress: 0.00% complete, ETA 00:02:30
# Fork: 1 of 1
# Warmup Iteration   1: 9.691 ms/op
# Warmup Iteration   2: 7.737 ms/op
Iteration   1: <failure>

org.neo4j.driver.exceptions.ClientException: Unable to read response from server: Expected a struct, but got: 2f
        at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:127)
        at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:99)
        at org.neo4j.driver.internal.StandardTransaction.run(StandardTransaction.java:121)
        at com.neueda.neo4j.driver.client.communication.transport.ndp.executors.NdpCommandExecutor.executeInStream(NdpCommandExecutor.java:67)
        at com.neueda.neo4j.driver.client.ServerGraphDatabaseService.execute(ServerGraphDatabaseService.java:276)
        at com.neueda.neo4j.driver.client.ServerGraphDatabaseService.execute(ServerGraphDatabaseService.java:261)
        at com.neueda.neo4j.driver.tests.perf.bench.GetNodesBenchmark.getNodesNdp(GetNodesBenchmark.java:60)
        at com.neueda.neo4j.driver.tests.perf.bench.generated.GetNodesBenchmark_getNodesNdp.getNodesNdp_avgt_jmhStub(GetNodesBenchmark_getNodesNdp.java:213)
        at com.neueda.neo4j.driver.tests.perf.bench.generated.GetNodesBenchmark_getNodesNdp.getNodesNdp_AverageTime(GetNodesBenchmark_getNodesNdp.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:452)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:434)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.driver.internal.packstream.PackStream$Unexpected: Expected a struct, but got: 2f
        at org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:471)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:352)
        at org.neo4j.driver.internal.connector.socket.SocketClient.send(SocketClient.java:113)
        at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:101)
        ... 18 more


<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 24 seconds more...>
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 19 seconds more...>
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 14 seconds more...>
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 9 seconds more...>
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 4 seconds more...>
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 0 seconds more...>
<shutdown timeout of 30 seconds expired, forcing forked VM to exit>

# Run complete. Total time: 00:02:34
```

----------------------
As a side node, several points regarding benchmark results:
- NDP is significantly faster than default REST API on small result set
- NDP became worse on bigger data size. With `X` = 100, NDP has same performance numbers as REST API.
- When `X` = 500 it became even worse. 

As I see, even if `Result` has stream-like API, currently driver fetch all records and then returns them.

But, anyway, NDP performance looks great, when they are no data transfer involved.

#### Create node benchmark.
Note: NDP and DB benchmarks share same top-level layer.
NDP - neo4j-java-driver is used as transport
DB - Unmanaged extension + HTTP + Kryo is used as transport

```
Benchmark                                Mode  Cnt  Score   Error  Units
CreateNodeBenchmark.createEmptyNodeDb    avgt    3  5.731 ± 6.670  ms/op
CreateNodeBenchmark.createEmptyNodeNdp   avgt    3  1.209 ± 0.635  ms/op
CreateNodeBenchmark.createEmptyNodeRest  avgt    3  2.338 ± 0.699  ms/op
```

#### Get single node benchmark
Same as above.
```
Benchmark                       Mode  Cnt  Score    Error  Units
GetNodesBenchmark.getNodesDb    avgt    3  6.311 ± 11.044  ms/op
GetNodesBenchmark.getNodesNdp   avgt    3  0.465 ±  0.402  ms/op
GetNodesBenchmark.getNodesRest  avgt    3  1.377 ±  0.316  ms/op
```

**Comment by nigelsmall** [comment]
Thanks for your interest in the new binary protocol and for such detailed feedback!

Please note though that this component is still under _very_ heavy internal development and testing and as such is a long way from general availability. For that reason, don't read too much into any performance figures or comparisons right now as the software available has not undergone any rounds of optimisation yet.

Cheers
Nigel

**Comment by FylmTM** [comment]
@nigelsmall Thanks for explanation. 
I understand that. 
Anyway, everything looks great, as far as it is :)

**Comment by jakewins** [comment]
@FylmTM are you able to re-create this issue, or was this something that happened because of the Neo4j server / driver version mismatch you mentioned in another issue?

If you can recreate it, please let us know what queries you're running and we'll try and replicate and fix it here.

On the performance: I *think* that this is due to one of the really cool things happening in cypher for 2.3/3.0. The new cypher runtime basically writes java programs and compiles them on the fly, leading to really cool performance benefits. The REST API has a new method for hooking into that plugged in, and we haven't plugged it in in NDP yet. There's a PR coming up to do that though :)

**Comment by FylmTM** [comment]
@jakewins Yes, I can re-create this issue. 
I'll try to create playground-type project tomorrow, so you can try this on your own.

**Comment by jakewins** [comment]
@FylmTM did you get any further on recreating the issue?

**Comment by FylmTM** [comment]
Hi @jakewins ,

Sorry for the long delay (was in vacation). Unfortunately I was unable to spend time on this due to time constraints. Currently NDP is not our high-priority target. 
I think this issue can be closed for now.
