### ISSUE TITLE
Opening concurrent sessions throws various exceptions

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j-java-driver#313]
The following code 

```
public class ConcurrentSessions {

    private static String query = "MATCH (n) return n";
    public static void main(String[] args) throws InterruptedException {
        Driver driver = GraphDatabase.driver( "bolt://localhost:7687", AuthTokens.basic( "neo4j", "neo" ),
                Config.build().withEncryptionLevel( Config.EncryptionLevel.NONE ).toConfig() );

        Set<Integer> sessions = new HashSet<>();
        ExecutorService executorService = Executors.newFixedThreadPool(1000);
        for (int i=0; i<1000;i++) {
            executorService.execute(() -> {
                try (Session session = driver.session()) {
                    try ( Transaction tx = session.beginTransaction() ) {
                        sessions.add(session.hashCode());
                        StatementResult result = tx.run( query);
                        result.consume();
                        tx.success();
                    }
                }
            });
        }
        executorService.shutdown();
        executorService.awaitTermination(5, TimeUnit.MINUTES);
        driver.close();
        System.out.println(sessions.size());
    }
}
```
throws either one of these two exceptions-

1. 
```
java.net.BindException: Address already in use
        at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_31]
        at sun.nio.ch.Net.connect(Net.java:457) ~[na:1.8.0_31]
        at sun.nio.ch.Net.connect(Net.java:449) ~[na:1.8.0_31]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647) ~[na:1.8.0_31]
        at org.neo4j.driver.internal.net.SocketClient$ChannelFactory.create(SocketClient.java:291) ~[neo4j-java-driver-1.1.0.jar:1.1.0-cec0652af796424e52867c859006da79b62d2ded]
        at org.neo4j.driver.internal.net.SocketClient.start(SocketClient.java:124) ~[neo4j-java-driver-1.1.0.jar:1.1.0-cec0652af796424e52867c859006da79b62d2ded]
```

2. 

```
SEVERE: ~~ [ERROR] You are using a session from multiple locations at the same time, which is not supported. If you want to use multiple threads, you should ensure that each session is used by only one thread at a time. One way to do that is to give each thread its own dedicated session.
```

Using version 1.1.0 and Neo4j 3.0.8

**Comment by lutovich** [comment]
Hi @luanne,

Thanks for reporting this problem. Could you please try java driver 1.1.1? I believe second problem should be fixed there. `ConcurrencyGuardingConnection` used to not allow concurrent `#close()` calls which are fine and possible in your case via `driver.close()`.

I can reproduce first problem only by adding `Thread.sleep(500)` after `tx.close()` but before `session.close()`. This is probably related to the amount of concurrent socket connections and is somehow OS dependent.

It is probably good to make `sessions` a `ConcurrentHashMap`. I've noticed couple `ClassCastExceptions` coming from `HashMap` caused by concurrent inserts.

**Comment by luanne** [comment]
Thanks @lutovich, I'll try 1.1.1 today and let you know. Thanks for the tip about the OS dependent socket connections- will look into it.
For `sessions`, it was just for the purpose of the test, throwing that away ;-)

**Comment by luanne** [comment]
Upgrading to 1.1.1 seems to have fixed the issue, thanks.

**Comment by lutovich** [comment]
@luanne glad it helped! Thanks.
