### ISSUE TITLE
Underscores in URI cause NullPointerExceptions

### ISSUE THREAD

**Issue by RobinMcCorkell** [neo4j/neo4j-java-driver#323]
I'm running a Neo4j application with the Bolt driver on GitLab's CI, where attached Docker services are referenced with hostnames including underscores (specifically double underscores to replace forward slashes in the Docker image name). This causes the Bolt driver to throw NullPointerExceptions:

```
   org.neo4j.ogm.exception.ConnectionException: Error connecting to graph database using Bolt
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.newSession(BoltDriver.java:101)
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.newTransaction(BoltDriver.java:73)
        at org.neo4j.ogm.session.transaction.DefaultTransactionManager.openTransaction(DefaultTransactionManager.java:71)
        at org.neo4j.ogm.session.transaction.DefaultTransactionManager.openTransaction(DefaultTransactionManager.java:57)
        at org.neo4j.ogm.drivers.bolt.request.BoltRequest.executeRequest(BoltRequest.java:153)
        at org.neo4j.ogm.drivers.bolt.request.BoltRequest.execute(BoltRequest.java:81)
        at org.neo4j.ogm.session.delegates.DeleteDelegate.purgeDatabase(DeleteDelegate.java:265)
        at org.neo4j.ogm.session.Neo4jSession.purgeDatabase(Neo4jSession.java:417)
        at uk.ac.cam.cl.part1b1617.kilo.graph.GraphIntegrationTestBase.setUp(GraphIntegrationTestBase.java:14)
        at uk.ac.cam.cl.part1b1617.kilo.graph.JobManagerServiceImplIntegrationTest.setUp(JobManagerServiceImplIntegrationTest.java:19)

        Caused by:
        java.lang.NullPointerException
            at org.neo4j.driver.internal.net.BoltServerAddress.hashCode(BoltServerAddress.java:91)
            at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
            at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.pool(SocketConnectionPool.java:129)
            at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquire(SocketConnectionPool.java:109)
            at org.neo4j.driver.internal.DirectDriver.newSessionWithMode(DirectDriver.java:49)
            at org.neo4j.driver.internal.BaseDriver.session(BaseDriver.java:62)
            at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.newSession(BoltDriver.java:97)
            ... 9 more
```

Verified locally with a hostname `a_b` which fails, and `a-b` which succeeds (well, failed with an unresolved host, but that's expected). Full URI would be `bolt://a_b:7687`

**Comment by lutovich** [comment]
Hi @Xenopathic,

Thanks for reporting this problem.
We simply use `URI` class to parse the given uri and create `BoltServerAddress` from it.
Interestingly `URI.create( "bolt://a_b:7687" ).getHost()` returns `null`. This seems to be a JDK issue, see http://bugs.java.com/view_bug.do?bug_id=6587184.

We will investigate how to work around this problem. Is it possible for you to switch to `-` instead of `_` for now?

**Comment by RobinMcCorkell** [comment]
@lutovich Yes, thankfully GitLab CI also provides host aliases without underscores, so I don't have any problems, just thought that this was an interesting issue that should be raised as a bug

**Comment by technige** [comment]
Thanks for raising this, I was previously unaware that Docker took this approach with URIs.

The RFCs relating to URI syntax, and more specifically those related to host naming, permit only alphanumerics, hyphens and dots in this portion of the URI however. Given that, I'm going to close this issue as a _wontfix_. We would be fighting something of an uphill battle with URI parsing libraries across all our supported languages if we chose to support this. I see this as something of a Docker quirk/issue instead.
