### ISSUE TITLE
BoltServerAddress throwing exception for bolt address from neo4j documentation

### ISSUE THREAD

**Issue by vigorouscoding** [neo4j/neo4j-java-driver#364]
I don't know if this is the correct place for this, as it touches neo4j-java-driver and neo4j-bolt, so if this is the wrong place, thanks for kindly pointing me in the correct direction!

----

I cant get the Bolt connector to work as described in https://neo4j.com/docs/java-reference/current/#tutorials-java-embedded-bolt 

When using `.setConfig( bolt.address, "localhost:7687");`, the following exception is thrown (tested with `neo4j-java-driver-1.2.1` and `neo4j-java-driver-1.3.0-rc1` )

    Invalid URI format `localhost:7689`
    java.lang.IllegalArgumentException
        at org.neo4j.driver.internal.net.BoltServerAddress.from(BoltServerAddress.java:47)
        at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:57)
        at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:132)
        at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:114)
        at org.structr.bolt.BoltDatabaseService.initialize(BoltDatabaseService.java:132)
        at org.structr.bolt.NodeWrapperTest.testDeleteException(NodeWrapperTest.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:45)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

The last working configuration was with `bolt.address = "bolt://localhost:7689"`, `neo4j-bolt-3.0.9` and `neo4j-java-driver-1.2.1`

From `neo4j-bolt-3.0.9` to `neo4j-bolt-3.1.0` a change was made to `org.neo4j.bolt.transport.NettyServer` in line 99, which (I think) causes this problem:

**3.0.9**

    new ServerBootstrap()
            .[...]
            .bind( initializer.address().getHost(), initializer.address().getPort() )

**3.1.0**

    new ServerBootstrap()
            .[...]
            .bind( initializer.address().socketAddress() )

When using our old `bolt.address = "bolt://localhost:7689"`, this change leads to an exception because the InetSocketAddress created from this is unresolved.

When using the address from the example `bolt.address = "localhost:7689"`, the created InetSocketAddress can be resolved but the aforementioned exception is thrown.

Do you have any advice for this?

**Comment by zhenlineo** [comment]
Is it working for you if you have `"localhost:7689"` in the server, while `"bolt://localhost:7689"` in the driver?
* Server:
```.setConfig( bolt.address, "localhost:7687");```
* Driver:
```GraphDatabase.driver("bolt://localhost:7687", ...);```

**Comment by vigorouscoding** [comment]
Thank you for the blazingly fast reply - I must have been blind from the debugging to not have figured out this simple solution. We'll update our code accordingly.

Perhaps someone could add this to the documentation so others don't fall into the same trap :)
