### ISSUE TITLE
Exception while executing statement with PROFILE and parameters

### ISSUE THREAD

**Issue by rjbaucells** [neo4j/neo4j-java-driver#416]
Driver version: 
````
<dependency>
    <groupId>org.neo4j.driver</groupId>
    <artifactId>neo4j-java-driver</artifactId>
    <version>1.4.4</version>
</dependency>
````
Database version: ENTERPRISE EDITION 3.1.5

OS: Linux server.local 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The following program throws an exception when the statement is executed with the PROFILE clause and parameters:
````java
public static void main(String[] args) {
    //
    // CREATE (n:Test{values: ['T1','Other']})
    //
    // driver instance
    try (Driver driver = GraphDatabase.driver("bolt://localhost", AuthTokens.basic("neo4j", "neo4j"))) {
        // session
        try (Session session = driver.session()) {
            // transaction
            try (Transaction transaction = session.beginTransaction()) {
                // statement using PROFILE and NO parameter ==> OK
                // StatementResult statementResult = transaction.run("PROFILE MATCH (n:Test) WHERE (CASE WHEN ANY(x in n.values WHERE x =~ '^T-?\\\\d+$') THEN SUBSTRING(HEAD([x in n.values WHERE x =~ '^T-?\\\\d+$']), 1) ELSE '1' END = '1') RETURN ID(n) as C0 LIMIT 1");
                // statement using parameter ==> OK
                // StatementResult statementResult = transaction.run("MATCH (n:Test) WHERE (CASE WHEN ANY(x in n.values WHERE x =~ '^T-?\\\\d+$') THEN SUBSTRING(HEAD([x in n.values WHERE x =~ '^T-?\\\\d+$']), 1) ELSE '1' END = {p0}) RETURN ID(n) as C0 LIMIT 1", Collections.singletonMap("p0", "1"));
                // statement using PROFILE and parameter ==> FAIL
                StatementResult statementResult = transaction.run("PROFILE MATCH (n:Test) WHERE (CASE WHEN ANY(x in n.values WHERE x =~ '^T-?\\\\d+$') THEN SUBSTRING(HEAD([x in n.values WHERE x =~ '^T-?\\\\d+$']), 1) ELSE '1' END = {p0}) RETURN ID(n) as C0 LIMIT 1", Collections.singletonMap("p0", "1"));
                // loop results
                while (statementResult.hasNext()) {
                    // current record
                    Record record = statementResult.next();
                    // print record
                    System.out.println(record.get(0));
                }
                // process profile
                ResultSummary summary = statementResult.consume();
                if (summary.hasProfile()) {
                    // log information
                    System.out.println(summary.profile());
                }
                // commit
                transaction.success();
            }
        }
    }
}
````

Exception:
````
Exception in thread "main" org.neo4j.driver.v1.exceptions.DatabaseException: Illegal group reference
	at org.neo4j.driver.internal.net.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:83)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:470)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:431)
	at org.neo4j.driver.internal.net.SocketClient.receiveOne(SocketClient.java:191)
	at org.neo4j.driver.internal.net.SocketConnection.receiveOne(SocketConnection.java:217)
	at org.neo4j.driver.internal.net.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:165)
	at org.neo4j.driver.internal.net.pooling.PooledSocketConnection.receiveOne(PooledSocketConnection.java:183)
	at org.neo4j.driver.internal.InternalStatementResult.receiveOne(InternalStatementResult.java:335)
	at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:325)
	at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:193)
	at test.Program.main(Program.java:80)
````

Database log:
````
2017-10-10 15:52:49.584+0000 ERROR Client triggered an unexpected error [UnknownError]: Illegal group reference. See debug.log for more details, reference 7ad3067b-882e-49ca-83b1-ffc103712384.
````

Database debug.log:
````
2017-10-10 15:52:49.584+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Illegal group reference. See debug.log for more details, reference 7ad3067b-882e-49ca-83b1-ffc103712384.
2017-10-10 15:52:49.585+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Illegal group reference, reference 7ad3067b-882e-49ca-83b1-ffc103712384. Illegal group reference
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at scala.util.matching.Regex$Replacement$class.replace(Regex.scala:804)
	at scala.util.matching.Regex$MatchIterator$$anon$1.replace(Regex.scala:782)
	at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
	at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.util.matching.Regex.replaceAllIn(Regex.scala:473)
	at org.neo4j.cypher.internal.compiler.v3_1.planDescription.PlanDescriptionArgumentSerializer$.removeGeneratedNames(PlanDescriptionArgumentSerializer.scala:91)
	at org.neo4j.cypher.internal.compiler.v3_1.planDescription.PlanDescriptionArgumentSerializer$.serialize(PlanDescriptionArgumentSerializer.scala:36)
	at org.neo4j.cypher.internal.compatibility.CompatibilityPlanDescriptionFor3_1$$anonfun$arguments$1$$anonfun$apply$3.apply(CompatibilityFor3_1.scala:436)
	at org.neo4j.cypher.internal.compatibility.CompatibilityPlanDescriptionFor3_1$$anonfun$arguments$1$$anonfun$apply$3.apply(CompatibilityFor3_1.scala:436)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.neo4j.cypher.internal.compatibility.CompatibilityPlanDescriptionFor3_1$$anonfun$arguments$1.apply(CompatibilityFor3_1.scala:436)
	at org.neo4j.cypher.internal.compatibility.CompatibilityPlanDescriptionFor3_1$$anonfun$arguments$1.apply(CompatibilityFor3_1.scala:436)
	at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_1$runSafely$.apply(CompatibilityFor3_1.scala:192)
	at org.neo4j.cypher.internal.compatibility.CompatibilityPlanDescriptionFor3_1.arguments(CompatibilityFor3_1.scala:435)
	at org.neo4j.cypher.internal.javacompat.Description.getArguments(Description.java:72)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.convert(ExecutionPlanConverter.java:36)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.children(ExecutionPlanConverter.java:53)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.convert(ExecutionPlanConverter.java:38)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.children(ExecutionPlanConverter.java:53)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.convert(ExecutionPlanConverter.java:38)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.children(ExecutionPlanConverter.java:53)
	at org.neo4j.bolt.v1.runtime.cypher.ExecutionPlanConverter.convert(ExecutionPlanConverter.java:38)
	at org.neo4j.bolt.v1.runtime.cypher.CypherAdapterStream.accept(CypherAdapterStream.java:86)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:130)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:451)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.streamResult(TransactionStateMachine.java:274)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:450)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:233)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:98)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:135)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:122)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:94)
	at java.lang.Thread.run(Thread.java:748)
````

Filter explanation: 
- If the node.values contains a text that starts with 'T' followed by numbers, use the first occurrence of this value and remove the letter 'T'. Otherwise use a literal value.
- Compare result from case statement with the given parameter value.

I know that the statement can be written in a completely different way avoiding the exception (that is not the point). This is a simplification of a very large statement, using only the expression that triggers the exception. Commenting the problematic statement and enabling one of the other two versions will execute without problems returning the correct results.

It is the combination of the expression + PROFILE + parameter the one that triggers the error. It cannot be replicated on the Browser console since it does not support parameters.

**Comment by lutovich** [comment]
Hi @rjbaucells,

I can reproduce this problem with neo4j 3.2.5. Error is not quite related to the java driver because it originates on server during query execution. Parameters are supported in neo4j-browser starting from 3.2, you might want to try that.

Will notify Cypher team about this problem.
