### ISSUE TITLE
Numerous Connection Reset By Peer Errors

### ISSUE THREAD

**Issue by briantq** [neo4j/neo4j-java-driver#480]
I am running Neo4j 3.3.3 on a Google Compute Engine and referencing the server via a Java 8 Google App Engine Instance that uses neo4j-java-driver 1.5.1.  I have seen the following error quite often over the past months but it started happening every 5-10 minutes today. 

```
org.neo4j.driver.internal.logging.JULogger error: [0x8f4b2605] Fatal error occurred in the pipeline (JULogger.java:42)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.neo4j.driver.internal.shaded.io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at org.neo4j.driver.internal.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

I am not ruling out configuration or environment.  After getting the errors in the past, I have tried creating the Driver with 30s connection  timeouts and 1 minute liveness checks, but that hasn't seemed to do much to resolve the issue.

Based on a previous bug report I checked the server logs (debug.log) but it did not appear to give me much insight.  What information should I try to gather to diagnose the problem?

**Comment by lutovich** [comment]
Hi @briantq,

"Connection reset by peer" usually happens when driver's long-lived TCP connection is closed by the other side. It can be closed either by neo4j database or by network equipment (load balancer, proxy, etc.) that sits in-between driver and database.

It looks like Google Compute Engine has idle TCP connection timeout set to 10 minutes by default: https://cloud.google.com/compute/docs/troubleshooting/general-tips#communicatewithinternet. Documentation suggests tuning TCP keep-alive instance option. Driver and database already open sockets with SO_KEEPALIVE set to `true` so this is worth to try.

You could also set liveness check to zero, so that connections will always be tested for validity when acquired from the connection pool. However, it seems like 1 minute timeout should've helped given that default idle timeout is 10 minutes.

It is also possible to use transaction functions API that automatically retries on network failures https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-transaction-functions.

Hope this helps!

**Comment by briantq** [comment]
@lutovich Thank you for doing that research!  I appreciate you really helping to solve the problem rather than just provide a bit of information!

One other piece of information that I should mention is that I have a health check that should be exercising the Neo4j connection every 60 seconds.  I would have thought this would help keep the connection open. 

Based on what you said, it sounds like an environmental issue that I should contact Google.  Are there any log files or logging that I could add that would help prove it is a network issue?  I figure that might help the conversation if there is more information I could provide.

Thanks again!

**Comment by lutovich** [comment]
@briantq driver has a connection pool and it's not always guaranteed that it'll contain just a single connection. Especially if driver is used by multiple threads. Health check would then need to excise all idle connections, possibly from multiple threads. Liveness check of zero should be the most reliable way to ensure connection is alive. It could, of course, die right after the check and still cause an exception. I'd try `withConnectionLivenessCheckTimeout(0, TimeUnit.SECONDS)` first, even without changing the Google Compute Engine config, this seems to be the easiest option.

You could use tcpdump to record all incoming and outgoing packets for the application. According to [link](https://technet.microsoft.com/en-us/library/cc957018.aspx) error "Connection reset by peer" should be visible in the tcpdump as an RST packet. Database should write to the `debug.log` when it closes the connection. If there are no such logs and tcpdump mentions RST packet then connection has probably been closed by the network equipment.

**Comment by briantq** [comment]
I'll close this issue to get it off your backlog as it is not a Neo4j issue.

@lutovich Thank you again for your help!  I do appreciate all the effort you put in to research another environment, I truly appreciate it!
