### ISSUE TITLE
Error using foreach to merge on items in an empty list.

### ISSUE THREAD

**Issue by vturlington** [neo4j/neo4j-java-driver#491]
```
UNWIND [{list:[],mergeProp:'test'}] AS input
MERGE (nodeRef0:NodeLabel0 {mergeProp: input.mergeProp})
WITH nodeRef0, input WHERE exists(input.list) AND size(input.list) > 0
FOREACH (i IN input.list |
  MERGE (nodeRef1:NodeLabel1 {mergeProp: i})
  MERGE (nodeRef0)-[:edge]->(nodeRef1)
)
```

This is an example query that will successfully merge for NodeLabel0, but when an attempt to merge on NodeLabel1 is made, this error is thrown:

```
org.neo4j.driver.v1.exceptions.ClientException: Cannot merge node using null property value for mergeProp
	at org.neo4j.driver.internal.net.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:76)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:470)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:431)
	at org.neo4j.driver.internal.net.SocketClient.receiveOne(SocketClient.java:196)
	at org.neo4j.driver.internal.net.SocketClient.receiveAll(SocketClient.java:190)
	at org.neo4j.driver.internal.net.SocketConnection.receiveAll(SocketConnection.java:203)
	at org.neo4j.driver.internal.net.SocketConnection.sync(SocketConnection.java:157)
	at org.neo4j.driver.internal.net.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:137)
	at org.neo4j.driver.internal.net.pooling.PooledSocketConnection.sync(PooledSocketConnection.java:157)
	at org.neo4j.driver.internal.ExplicitTransaction.close(ExplicitTransaction.java:115)
	at org.neo4j.driver.internal.NetworkSession$1.get(NetworkSession.java:274)
	at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:82)
	at org.neo4j.driver.internal.NetworkSession.transaction(NetworkSession.java:254)
	at org.neo4j.driver.internal.NetworkSession.writeTransaction(NetworkSession.java:195)
	at com.anivive.util.neo.NeoGatewayBoltImpl.writeTransaction(NeoGateway.kt:70)
	at com.anivive.util.neo.NeoGatewayBoltImpl.executeQuery(NeoGateway.kt:60)
	at com.anivive.util.neo.NeoGatewayBoltImpl.executeQuery(NeoGateway.kt:33)
	at com.anivive.util.neo.NeoGateway.executeQuery$default(NeoGateway.kt:30)
	at com.anivive.crunchbase.csv.CrunchBaseImporterMain$crunch$3$1$1.run(CrunchBaseImporterMain.kt:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The properties are passed in as parameters to a Transaction object.

**Comment by vturlington** [comment]
Was mistaken on the error. Came from a different source. My apologies.
