### ISSUE TITLE
Random Could not compile query due to insanely frequent schema changes errors in our build

### ISSUE THREAD

**Issue by graemerocher** [neo4j/neo4j-java-driver#552]
With the latest version of the driver we get random errors like the following:

```
org.neo4j.driver.v1.exceptions.DatabaseException: Could not compile query due to insanely frequent schema changes
    at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:122)
    at org.neo4j.driver.internal.ExplicitTransaction.close(ExplicitTransaction.java:117)
    at grails.gorm.tests.GormDatastoreSpec.cleanup(GormDatastoreSpec.groovy:91)
```

This did not occur in earlier versions of the driver.

**Neo4j Version:** 3.5.0 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Java driver 1.7.2
**Operating System:** Mac OS X

### Steps to reproduce
1. git clone git@github.com:grails/gorm-neo4j.git
2. ./gradlew grails-datastore-gorm-neo4j:test
3. See random errors (sometimes build passes)

**Comment by zhenlineo** [comment]
This is very likely not a driver issue as the driver does not process the query string. Could you run with your tests with 3.5 neo4j and 1.6 java driver to verify that is is not a driver issue?

P.S. I tried to reproduce it locally, but I got some missing test dependency errors:
```
Execution failed for task ':grails-datastore-gorm-neo4j:compileGroovy'.
> Could not resolve all files for configuration ':grails-datastore-gorm-neo4j:compileClasspath'.
   > Could not find neo4j-kernel-tests.jar (org.neo4j:neo4j-kernel:3.5.0).
     Searched in the following locations:
         file:/Users/xx/.m2/repository/org/neo4j/neo4j-kernel/3.5.0/neo4j-kernel-3.5.0-tests.jar
   > Could not find neo4j-io-tests.jar (org.neo4j:neo4j-io:3.5.0).
     Searched in the following locations:
         file:/Users/xx/.m2/repository/org/neo4j/neo4j-io/3.5.0/neo4j-io-3.5.0-tests.jar
   > Could not find neo4j-common-tests.jar (org.neo4j:neo4j-common:3.5.0).
     Searched in the following locations:
         file:/Users/xx/.m2/repository/org/neo4j/neo4j-common/3.5.0/neo4j-common-3.5.0-tests.jar
```
I am confused why it does not go to [maven central](http://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/3.5.0/) to retry the missing files. Pls let me know if I missed something important.

**Comment by graemerocher** [comment]
as mentioned the issue started occurring after upgrading the driver from 1.6 to 1.7

**Comment by zhenlineo** [comment]
Hi @graemerocher This `DatabaseException` indicates that this error happened on the database side. Could you have a look at the database log to see if there is any error messages related to the driver error?

Also this new error message was added in 3.5.0, so it is likely that it is something changed in the Cypher execution engine in 3.5.0. It would be really appreciated if you can try 3.4 database with 1.7 driver, and 3.5 database with 1.6 driver to verify that this is only an issue with 3.5 database.

I tried to run your project on my machine, but I have all strange errors to compile and run tests. After the test jar dependency problem, I also have some problems to start jersey server for tests and I got `Cannot find firefox binary in PATH` error. It would be really helpful if you have more detailed steps for users new to gradle to compile and run your project?

I am also moving this issue to Neo4j/Neo4j to see if we've know we have such an issue on the server side.
