### ISSUE TITLE
Configuring driver w/ Aura & neo4j+s fails: Failed to perform multi-databases feature detection

### ISSUE THREAD

**Issue by sdaschner** [neo4j/neo4j-java-driver#986]
When constructing a connection to a Neo4J Aura instance with Neo4J-OGM and `Configuration`, creation of the driver fails.

## To reproduce

```java
public class ConnTest {

    public static void main(String[] args) {

        // Aura Free instance
        String databaseUri = "neo4j+s://xxxxxx00.databases.neo4j.io";
        String username = "neo4j";
        String password = "[...]";

        Configuration neoConfig = new Configuration.Builder()
                .uri(databaseUri)
                .credentials(username, password)
                .useNativeTypes()
                .build();

        SessionFactory sessionFactory = new SessionFactory(neoConfig, SessionFactoryProducer.PACKAGES);

        Session session = sessionFactory.openSession();
        Iterable<SomeEntity> entities = session.query(SomeEntity.class, "MATCH (n:SomeEntity) RETURN n;", Map.of());
        System.out.println("entities = " + entities);
    }
}
```

Funny enough, using `neo4j://xxx...` as URL seems to work, once I use `neo4j+s` it fails with the following exception:

```
Exception in thread "main" org.neo4j.ogm.exception.ConnectionException: Could not create driver instance
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.initializeDriver(BoltDriver.java:174)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.checkDriverInitialized(BoltDriver.java:138)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.lambda$null$0(BoltDriver.java:124)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver$$Lambda$156/0x00000000c0acbb60.apply(Unknown Source)
	at org.neo4j.ogm.session.transaction.DefaultTransactionManager.openTransaction(DefaultTransactionManager.java:75)
	at org.neo4j.ogm.session.Neo4jSession.beginTransaction(Neo4jSession.java:530)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:580)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:558)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.executeAndMap(ExecuteQueriesDelegate.java:150)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:117)
	at org.neo4j.ogm.session.Neo4jSession.query(Neo4jSession.java:419)
	at com.sebastian_daschner.ConnTest.main(ConnTest.java:32)
Caused by: org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to database management service, ensure the database is running and that there is a working network connection to it.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:113)
	at org.neo4j.driver.internal.InternalDriver.verifyConnectivity(InternalDriver.java:159)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.initializeDriver(BoltDriver.java:170)
	... 11 more
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer.lambda$verifyConnectivity$3(LoadBalancer.java:123)
		at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer$$Lambda$206/0x00000000c0bc7ab8.apply(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
		at org.neo4j.driver.internal.util.Futures.lambda$asCompletionStage$0(Futures.java:97)
		at org.neo4j.driver.internal.util.Futures$$Lambda$201/0x00000000c0bc6940.operationComplete(Unknown Source)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:853)
Caused by: org.neo4j.driver.exceptions.ServiceUnavailableException: Failed to perform multi-databases feature detection with the following servers: [c30ccb07.databases.neo4j.io(34.78.76.49):7687]
	at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer.supportsMultiDb(LoadBalancer.java:153)
	at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer.verifyConnectivity(LoadBalancer.java:117)
	at org.neo4j.driver.internal.SessionFactoryImpl.verifyConnectivity(SessionFactoryImpl.java:73)
	at org.neo4j.driver.internal.InternalDriver.verifyConnectivityAsync(InternalDriver.java:141)
	... 13 more
	Suppressed: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.
		at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:54)
		at org.neo4j.driver.internal.async.connection.HandshakeHandler.channelInactive(HandshakeHandler.java:82)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
		at org.neo4j.driver.internal.shaded.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
		at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:853)
```

- Neo4j version: Neo4J Aura Free
- Driver version: `4.3.4`
- Neo4J OGM: `3.2.25`

Related to quarkusio/quarkus#19412
CC: @jexp

**Comment by injectives** [comment]
Thanks for reporting the issue.

Would you be able to provide steps to reproduce with plain driver since this issue is reported in the driver repository please?

I tried the following snippet that worked for me:
```
try ( Driver driver =
              GraphDatabase.driver( "neo4j+s://redacted",
                                    AuthTokens.basic( USERNAME, PASSWORD ) );
      Session session = driver.session() )
{
    driver.verifyConnectivity();
    session.run( "RETURN 1" ).forEachRemaining( System.out::println );
}
```

**Comment by injectives** [comment]
Based on the provided stacktrace, it seems like `verifyConnectivity` fails with the following error:
```
org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to database management service, ensure the database is running and that there is a working network connection to it.
```
The error seems to be caused by `supportsMultiDb` downstream call failing with the following error:
```
org.neo4j.driver.exceptions.ServiceUnavailableException: Failed to perform multi-databases feature detection with the following servers: [c30ccb07.databases.neo4j.io(34.78.76.49):7687]
```
At this point, the `supportsMultiDb` call tries acquiring a working connection to router servers.
The latter error seems to be caused by the following error:
```
org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.
```
that is caused by Netty channel going 'inactive' during `Bolt` handshake.

In simple words, it looks like connections to routing servers get aborted for whatever reason during `Bolt` handshake causing the `verifyConnectivity` failure.

**Comment by injectives** [comment]
This issue may be environmental and it would be useful to narrow down its scope. Hence, the following steps may help:
- keep the `neo4j+s` scheme
- reproduce with plain driver
- try reproducing on different environments (local, container, remote, etc.)
- try different Aura instance

Unfortunately, both me and @michael-simons could not reproduce it so far.

**Comment by michael-simons** [comment]
For the record: I 

```java
package com.example.ogmaura;

import java.util.Map;

import org.neo4j.ogm.config.Configuration;
import org.neo4j.ogm.session.Session;
import org.neo4j.ogm.session.SessionFactory;

public class OgmauraApplication {

	public static void main(String[] args) {
		// Aura Free instance
		String databaseUri = "neo4j+s://9425e19e.databases.neo4j.io";
		String username = "neo4j";
		String password = "XXX";

		Configuration neoConfig = new Configuration.Builder()
			.uri(databaseUri)
			.credentials(username, password)
			.useNativeTypes()
			.build();

		SessionFactory sessionFactory = new SessionFactory(neoConfig, "com.example.ogmaura");

		Session session = sessionFactory.openSession();
		Iterable<SomeEntity> entities = session.query(SomeEntity.class, "MATCH (n:SomeEntity) RETURN n;", Map.of());
		System.out.println("entities = " + entities);
	}
}
```

defined by

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>ogmaura</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ogmaura</name>
	<description>ogmaura</description>
	
	<properties>
		<java.version>11</java.version>
		<neo4j-ogm.version>3.2.25</neo4j-ogm.version>
		<neo4j-java-driver.version>4.3.4</neo4j-java-driver.version>
		<maven.compiler.release>${java.version}</maven.compiler.release>
	</properties>
	<dependencies>

		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j-ogm-core</artifactId>
			<version>${neo4j-ogm.version}</version>
		</dependency>
		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j-ogm-bolt-driver</artifactId>
			<version>${neo4j-ogm.version}</version>
		</dependency>
		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j-ogm-bolt-native-types</artifactId>
			<version>${neo4j-ogm.version}</version>
		</dependency>
		<dependency>
			<groupId>org.neo4j.driver</groupId>
			<artifactId>neo4j-java-driver</artifactId>
			<version>${neo4j-java-driver.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
			</plugin>
		</plugins>
	</build>

</project>
```

works agains "my" free aura instance.

**Comment by sdaschner** [comment]
@michael-simons 
Your example fails for me if I use my `neo4j://c30ccb07.databases.neo4j.io`, however, now it works when I'm using `neo4j+s`, so now I'm even more confused...

The error with `neo4j` scheme is:

```
/opt/java/jdk-16.0.1+9/bin/java -javaagent:/opt/intellij-idea-ultimate-edition/lib/idea_rt.jar=38915:/opt/intellij-idea-ultimate-edition/bin -Dfile.encoding=UTF-8 -classpath /tmp/test-project/target/classes:/home/sebastian/.m2/repository/org/neo4j/neo4j-ogm-core/3.2.25/neo4j-ogm-core-3.2.25.jar:/home/sebastian/.m2/repository/org/neo4j/neo4j-ogm-api/3.2.25/neo4j-ogm-api-3.2.25.jar:/home/sebastian/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.9/jackson-databind-2.9.9.jar:/home/sebastian/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/home/sebastian/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.jar:/home/sebastian/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.jar:/home/sebastian/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.9/jackson-datatype-jsr310-2.9.9.jar:/home/sebastian/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/sebastian/.m2/repository/org/apache/commons/commons-lang3/3.8/commons-lang3-3.8.jar:/home/sebastian/.m2/repository/io/github/classgraph/classgraph/4.8.86/classgraph-4.8.86.jar:/home/sebastian/.m2/repository/org/neo4j/neo4j-ogm-bolt-driver/3.2.25/neo4j-ogm-bolt-driver-3.2.25.jar:/home/sebastian/.m2/repository/org/neo4j/neo4j-ogm-bolt-native-types/3.2.25/neo4j-ogm-bolt-native-types-3.2.25.jar:/home/sebastian/.m2/repository/org/neo4j/driver/neo4j-java-driver/4.3.4/neo4j-java-driver-4.3.4.jar:/home/sebastian/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar com.sebastian_daschner.test_project.OgmauraApplication
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Aug 17, 2021 1:41:52 PM org.neo4j.driver.internal.logging.JULogger info
INFO: Routing driver instance 1410000237 created for server address c30ccb07.databases.neo4j.io:7687
Aug 17, 2021 1:41:52 PM org.neo4j.driver.internal.logging.JULogger info
INFO: Closing driver instance 1410000237
Aug 17, 2021 1:41:52 PM org.neo4j.driver.internal.logging.JULogger info
INFO: Closing connection pool towards c30ccb07.databases.neo4j.io(34.78.76.49):7687
Exception in thread "main" org.neo4j.ogm.exception.ConnectionException: Could not create driver instance
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.initializeDriver(BoltDriver.java:174)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.checkDriverInitialized(BoltDriver.java:138)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.lambda$null$0(BoltDriver.java:124)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver$$Lambda$165/0x00000000606fbe90.apply(Unknown Source)
	at org.neo4j.ogm.session.transaction.DefaultTransactionManager.openTransaction(DefaultTransactionManager.java:75)
	at org.neo4j.ogm.session.Neo4jSession.beginTransaction(Neo4jSession.java:530)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:580)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:558)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.executeAndMap(ExecuteQueriesDelegate.java:150)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:117)
	at org.neo4j.ogm.session.Neo4jSession.query(Neo4jSession.java:419)
	at com.sebastian_daschner.test_project.OgmauraApplication.main(OgmauraApplication.java:26)
Caused by: org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to database management service, ensure the database is running and that there is a working network connection to it.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:113)
	at org.neo4j.driver.internal.InternalDriver.verifyConnectivity(InternalDriver.java:159)
	at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.initializeDriver(BoltDriver.java:170)
	... 11 more
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer.lambda$verifyConnectivity$3(LoadBalancer.java:123)
		at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer$$Lambda$196/0x00000000607fc028.apply(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
		at org.neo4j.driver.internal.util.Futures.lambda$asCompletionStage$0(Futures.java:97)
		at org.neo4j.driver.internal.util.Futures$$Lambda$191/0x00000000607fb578.operationComplete(Unknown Source)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:853)
Caused by: org.neo4j.driver.exceptions.ServiceUnavailableException: Failed to perform multi-databases feature detection with the following servers: [c30ccb07.databases.neo4j.io(34.78.76.49):7687]
	at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer.supportsMultiDb(LoadBalancer.java:153)
	at org.neo4j.driver.internal.cluster.loadbalancing.LoadBalancer.verifyConnectivity(LoadBalancer.java:117)
	at org.neo4j.driver.internal.SessionFactoryImpl.verifyConnectivity(SessionFactoryImpl.java:73)
	at org.neo4j.driver.internal.InternalDriver.verifyConnectivityAsync(InternalDriver.java:141)
	... 13 more
	Suppressed: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.
		at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:54)
		at org.neo4j.driver.internal.async.connection.HandshakeHandler.channelInactive(HandshakeHandler.java:82)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
		at org.neo4j.driver.internal.shaded.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
		at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:853)

Process finished with exit code 1

```

@injectives Same with your example, `neo4j+s` works now, `neo4j` doesn't... Maybe it's connected to my Aura instance?

**Comment by injectives** [comment]
It looks like it works for you now.

https://neo4j.com/docs/java-manual/current/client-applications/
See: Table 3. Neo4j Aura, secured with full certificate (`neo4j+s`)
```
This is the default (and only option) for Neo4j Aura
```

**Comment by michael-simons** [comment]
@sdaschner We got word from our Aura team that some (not all) free instances had issues yesterday. Maybe the original issue was just a coincidence.

**Comment by sdaschner** [comment]
Hmm, got it. It was just interesting, that with Quarkus the issue was exactly the other way around (with / without `+s`).

So leave for now or can I help to provide some more information to further investigate the `Failed to perform multi-databases feature detection` error?

**Comment by injectives** [comment]
At present, it seems like the issue was outside of the driver project.
Unless there is some additional information or you managed to discuss this with somebody from Aura, it may be better to reopen this issue if it happens again and seems to be related to the driver.
